#camera node
camera_topic: /kitti/camera_gray_left/image_raw
lidar_topic: /kitti/velo/pointcloud
#yolo
medel_path: "/home/zgq/Documents/model/yolo/"
yoloclassfile: "coco.names"
yoloModelConfiguration: "yolov4-tiny.cfg"
yoloModelWeights: "yolov4-tiny.weights"

confThreshold: 0.2
nmsThreshold: 0.4
bVis: false

